# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Revels 16' do

pod 'SVProgressHUD'
pod 'SDWebImage', '~>3.7'
pod 'KWTransition'
pod 'DGActivityIndicatorView'
pod 'PullToRefreshCoreText', '~> 0.2'

end

